export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_FINISH = 'ORDER_CREATE_FINISH';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET';

export const ORDER_PAY_PROCESS_REQUEST = 'ORDER_PAY_PROCESS_REQUEST';
export const ORDER_PAY_PROCESS_SUCCESS = 'ORDER_PAY_PROCESS_SUCCESS';
export const ORDER_PAY_PROCESS_FAIL = 'ORDER_PAY_PROCESS_FAIL';
export const ORDER_PAY_PROCESS_RESET = 'ORDER_PAY_PROCESS_RESET';

export const ORDER_LIST_CUSTOMER_REQUEST = 'ORDER_LIST_CUSTOMER_REQUEST';
export const ORDER_LIST_CUSTOMER_SUCCESS = 'ORDER_LIST_CUSTOMER_SUCCESS';
export const ORDER_LIST_CUSTOMER_FAIL = 'ORDER_LIST_CUSTOMER_FAIL';
export const ORDER_LIST_CUSTOMER_RESET = 'ORDER_LIST_CUSTOMER_RESET';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';
export const ORDER_LIST_RESET = 'ORDER_LIST_RESET';

export const ORDER_DELIVERY_PROCESS_REQUEST = 'ORDER_DELIVERY_PROCESS_REQUEST';
export const ORDER_DELIVERY_PROCESS_SUCCESS = 'ORDER_DELIVERY_PROCESS_SUCCESS';
export const ORDER_DELIVERY_PROCESS_FAIL = 'ORDER_DELIVERY_PROCESS_FAIL';
export const ORDER_DELIVERY_PROCESS_RESET = 'ORDER_DELIVERY_PROCESS_RESET';
