"""add payment provider table

Revision ID: 225e66cd8d44
Revises: bf30a3348bd9
Create Date: 2023-05-25 15:29:29.077350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225e66cd8d44'
down_revision = 'bf30a3348bd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_provider',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_provider_id'), 'payment_provider', ['id'], unique=False)
    op.add_column('payment_details', sa.Column('provider_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payment_details', 'payment_provider', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_details', type_='foreignkey')
    op.drop_column('payment_details', 'provider_id')
    op.drop_index(op.f('ix_payment_provider_id'), table_name='payment_provider')
    op.drop_table('payment_provider')
    # ### end Alembic commands ###
