"""add shipping price to Order table

Revision ID: 88684e13c7f5
Revises: 926210adb3cb
Create Date: 2023-05-04 14:28:55.971021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88684e13c7f5'
down_revision = '926210adb3cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('shipping_price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'shipping_price')
    # ### end Alembic commands ###
