"""replace backref to back_populates

Revision ID: aee06e2aaf0d
Revises: dbbb0d45a6ed
Create Date: 2023-04-28 10:31:40.679688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee06e2aaf0d'
down_revision = 'dbbb0d45a6ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
