"""change payment details table

Revision ID: bf30a3348bd9
Revises: f83705b014a3
Create Date: 2023-05-25 15:04:31.298988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf30a3348bd9'
down_revision = 'f83705b014a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order', 'payment_details', ['payment_id'], ['id'])
    op.add_column('payment_details', sa.Column('create_time', sa.DateTime(), nullable=False))
    op.alter_column('payment_details', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('payment_details', 'update_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('payment_details', 'email_address',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('payment_details', 'payment_details_id')
    op.drop_column('payment_details', 'payment_method_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_details', sa.Column('payment_method_type', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('payment_details', sa.Column('payment_details_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('payment_details', 'email_address',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('payment_details', 'update_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('payment_details', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('payment_details', 'create_time')
    op.drop_constraint(None, 'order', type_='foreignkey')
    # ### end Alembic commands ###
