"""add updated_on column to the Product DB

Revision ID: ce2396734618
Revises: a01484c553ee
Create Date: 2023-05-31 18:23:49.557076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2396734618'
down_revision = 'a01484c553ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('updated_on', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'updated_on')
    # ### end Alembic commands ###
