"""change Product user_id FK name

Revision ID: dbbb0d45a6ed
Revises: e16d44d723a4
Create Date: 2023-04-28 10:14:07.783401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbbb0d45a6ed'
down_revision = 'e16d44d723a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('product_ibfk_1', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'user', ['creator_id'], ['id'])
    op.drop_column('product', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_ibfk_1', 'product', 'user', ['user_id'], ['id'])
    op.drop_column('product', 'creator_id')
    # ### end Alembic commands ###
