"""add payment details table

Revision ID: f83705b014a3
Revises: 82e4756348c5
Create Date: 2023-05-05 12:06:16.477032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83705b014a3'
down_revision = '82e4756348c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_method_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('email_address', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_details_id'), 'payment_details', ['id'], unique=False)
    op.add_column('order', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'payment_details', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'payment_id')
    op.drop_index(op.f('ix_payment_details_id'), table_name='payment_details')
    op.drop_table('payment_details')
    # ### end Alembic commands ###
