"""new mig

Revision ID: 005039966b86
Revises: 25ef5d257004
Create Date: 2023-04-27 16:21:37.796881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005039966b86'
down_revision = '25ef5d257004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'product', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
