"""add user_id as foreign key to review table

Revision ID: 23e68341b6cf
Revises: 25ef5d257004
Create Date: 2023-04-27 14:23:54.745185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e68341b6cf'
down_revision = '25ef5d257004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
