"""add isActive column to the User table

Revision ID: 25ef5d257004
Revises: c9a87f31052e
Create Date: 2023-04-25 10:06:42.549785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25ef5d257004'
down_revision = 'c9a87f31052e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isActive', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('createdAt', sa.TIMESTAMP(), nullable=True))
    op.add_column('user', sa.Column('updatedAt', sa.TIMESTAMP(), nullable=True))
    op.drop_column('user', 'created_on')
    op.drop_column('user', 'updated_on')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_on', mysql.TIMESTAMP(), nullable=True))
    op.add_column('user', sa.Column('created_on', mysql.TIMESTAMP(), nullable=True))
    op.drop_column('user', 'updatedAt')
    op.drop_column('user', 'createdAt')
    op.drop_column('user', 'isActive')
    # ### end Alembic commands ###
