"""change products backref in User

Revision ID: 3a2c2e2bd737
Revises: 0f66ab6b33a7
Create Date: 2023-04-27 17:09:51.710187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2c2e2bd737'
down_revision = '0f66ab6b33a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
