"""Database creation

Revision ID: 95569cdf58ea
Revises: 
Create Date: 2023-04-24 15:03:51.311081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95569cdf58ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Review_id', table_name='Review')
    op.drop_table('Review')
    op.drop_index('ix_review_id', table_name='review')
    op.drop_table('review')
    op.drop_index('ix_Product_id', table_name='Product')
    op.drop_table('Product')
    op.drop_index('ix_product_id', table_name='product')
    op.drop_table('product')
    op.drop_index('ix_User_id', table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('brand', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('countInStock', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_User_id', 'User', ['id'], unique=False)
    op.create_table('product',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('brand', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('countInStock', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_on', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_product_id', 'product', ['id'], unique=False)
    op.create_table('Product',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('brand', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('countInStock', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Product_id', 'Product', ['id'], unique=False)
    op.create_table('review',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_review_id', 'review', ['id'], unique=False)
    op.create_table('Review',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Review_id', 'Review', ['id'], unique=False)
    # ### end Alembic commands ###
